language: node_js
node_js:
  - "node"
#env:
#  - MOZ_HEADLESS=1
#addons:
#  firefox: "latest"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq pandoc
script:
  - npm run build
  - npm run lint
  - npm run test
  - VERSION=$(node -p "require('./manifest.json').version") npm run lint-release
after_success:
  - npm run coverage
